source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

workspace 'DummyProject/Dummy.xcworkspace'

target 'DummyFramework' do
  project 'DummyProject/Dummy.xcodeproj'

  pod 'Alamofire',              '~> 4.5'
  pod 'CryptoSwift',            '~> 0.8'
  pod 'GzipSwift',              '~> 4.0'
  pod 'RxSwift',                '~> 4.0'
  pod 'SQLCipher/standard',     '~> 3.4'
  pod 'SQLite.swift/SQLCipher', '~> 0.11'
  pod 'SwiftyJSON',             '~> 3.1'
  pod 'YandexMobileMetrica',    '~> 2.9'
end
