source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

workspace 'DummyProject/Dummy.xcworkspace'

target 'DummyFramework' do
  project 'DummyProject/Dummy.xcodeproj'

  pod 'Alamofire', '~> 4.5'
end
