source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

workspace 'DummyProject/Dummy.xcworkspace'

target 'DummyFramework' do
  project 'DummyProject/Dummy.xcodeproj'

  pod 'Alamofire',                '~> 4.5'
  pod 'CryptoSwift',              '~> 0.8'
# pod 'Differentiator',           '~> 3.0'
  pod 'GzipSwift',                '~> 4.0'
  pod 'R.swift',                  '~> 4.0'  # R.swift.Library
# pod 'R.swift.Library',          '~> 4.0'
# pod 'RxCocoa',                  '~> 4.0'  # RxSwift
  pod 'RxDataSources',            '~> 3.0'  # Differentiator, RxCocoa
# pod 'RxSwift',                  '~> 4.0'
  pod 'SDWebImage',               '~> 4.2'
  pod 'Siren',                    '~> 3.1'
  pod 'SlideMenuControllerSwift', '~> 4.0'
  pod 'SQLCipher/standard',       '~> 3.4'
  pod 'SQLite.swift/SQLCipher',   '~> 0.11'
  pod 'SwiftReorder',             '~> 2.0'
  pod 'SwiftyJSON',               '~> 3.1'
  pod 'YandexMobileMetrica',      '~> 2.9'
end
